/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal projects. It is committed here
// because the app was scaffolded before local Node tooling was available.
